# MACHINE LEARNING
## GROUP COURSEWORK 4
### Group G: Joanna Andari, Karim Awad, Jiye Ren, Nirbhay Sharma, Qiuyue Zhang, Xiaoyan Zhou

For this assignment, we are going to 'scrape' data on Argentinian soccer players from the EA sports FIFA games website. It is important that you know how to scrape data from the web that is not available in a convenient form such as a CSV file.

### QUESTION 1
**Explore manually the website http://sofifa.com. Under the tab ‘All’, press on the any of the Argentinian flags (e.g. those corresponding to L. Messi or G. Higuain). Notice how the URL of the opened webpage changes to http://sofifa.com/players?na=52. Scrolling down, notice that not all players fit in one page. If you press ‘Next’, the new URL is http://sofifa.com/players?na=52&offset=80. Can you see the pattern? Next, select an individual player and notice how the URL changes. We want to download the numerical attributes available for all 640 Argentinian players.**

**ANSWER**                       
Yes we see the pattern of the offset is changing as we use the next page. The offset changes by 80 for every new page.

### QUESTION 2

**Explain in detail the code below.**

![fig2.png](images/fig2.png)

**In order to better understand the code, you may want to look at the following websites:                  
• https://www.crummy.com/software/BeautifulSoup/                           
• http://www.aivosto.com/vbtips/regex.html                            
• https://docs.python.org/2/library/re.html **

**ANSWER)**                
                           
Below is a detailed explanation of the working of the code given above:

**A) Initiate the lists**
* Create a list called $attributes$ and list all "attributes" data we need to get for our players
* Create a blank list called $links$, which stores the links of Argentinian Players

**B) Obtain the data for the players**
* Using the learnings from the Question 1, we set the initial link as "http://sofifa.com/players?na=52&offset=", and append it with the value of offsets [0, 80, 160,... and so on].
* We then send a GET request through HTTP using the requests.get function.  
* We then use the $BeautifulSoup$ package to parse through the contents of the page. Since it is a HTML page, we use the $html.parser$
* Now, we know from our HTML knowledge that the HTML tags starting with $< a$ are the links to the player detail page. So, we loop for all the link tags, and then append the $href$ value from every tag, to the $links$ list.
* We then modify the $links$ list to append "http://sofifa.com" to the link and thus making them directly accessible.

**C) Create pattern to match and get the attributes**
* We set a pattern in which the Create a list of all the "attributes" data we need to get for our players' names, and add attributes that we need to capture data for.
* We then re-compile the regular expression in order to use it repeatedly with the match() method. This also helps us to carry out multi-line parsing.

**D) Loop through the links and get the data**
* We process each link in $links$, and for each of them we create a HTML GET request, and then parse the RESPONSE using the $BeautifulSoup$ using its html parser.
* We then use the $match()$ function and get the value of all the required attributes and append it to the $rows$ list. 

**E) Create the data file**
* We create a pandas dataframe and then create a CSV file from it.

### QUESTION 3

**3) How would you change the code to download the first 480 English players instead?**

**ANSWER**
The link that we used to scrape data for Argentina players is "http://sofifa.com/players?na=52&offset=" where the attribute $na=52$ is for the country Argentina. To get the first 480 players of england, the following changes would be needed in the first for loop: 

1) First Line of the for loop:
* Set offset in the list [0, 80, 160, 240, 320, 400]; i.e. for $offset in [0, 80, 160, 240, 320, 400]$
* This will get the first 480 playaers

2) Second line of the for loop:
* Change the value for $na$ link to 14, i.e. "http://sofifa.com/players?na=14&offset='+offset="

The data was downloaded and saved as EnglandPlayers.csv and uploaded on GitHub to access.

### QUESTION 4

**4) Use the sklearn.cluster.KMeans Python class to cluster the players into 4 clusters.**

**ANSWER**                          
In order to create the clusters from the current players, let us first create a dataset of all the england players removing their names and the player link.

In [49]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

df = pd.read_csv('https://raw.githubusercontent.com/Karim01982/preparation/master/Autumn_term/Machine%20Learning/Assignment4/EnglandPlayers.csv')
df_names = df['name']
df_attributes = df.drop(['name','link'],axis=1)
df_attributes.head()

,Crossing,Finishing,Heading accuracy,Short passing,Volleys,Dribbling,Curve,Free kick accuracy,Long passing,Ball control,...,Penalties,Composure,Marking,Standing tackle,Sliding tackle,GK diving,GK handling,GK kicking,GK positioning,GK reflexes
0,73,64,58,84,64,82,80,72,80,84,...,65,80,61,63,65,6,15,15,9,11
1,11,16,12,36,12,21,12,14,40,26,...,42,59,16,13,11,81,83,72,78,85
2,77,81,75,81,84,73,84,81,82,80,...,84,88,48,51,37,10,11,13,8,7
3,86,63,74,79,63,78,81,81,74,80,...,90,81,78,81,78,8,15,10,13,12
4,81,57,62,76,64,79,64,57,66,76,...,57,75,82,84,85,10,11,8,13,13

Now, using KMeans method from sklearn.cluster, we create 4 clusters of the players. After doing that, we add names of the players as well as their KMean predictions.

In [50]:
kmeans = KMeans(n_clusters=4, random_state=0)
kmeans_test = kmeans.fit(df_attributes)
df_attributes['kmeans_prediction'] = kmeans_test.labels_
df_attributes['names'] = df_names
df_attributes.head()

,Crossing,Finishing,Heading accuracy,Short passing,Volleys,Dribbling,Curve,Free kick accuracy,Long passing,Ball control,...,Marking,Standing tackle,Sliding tackle,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,kmeans_prediction,names
0,73,64,58,84,64,82,80,72,80,84,...,61,63,65,6,15,15,9,11,0,Jack Wilshere
1,11,16,12,36,12,21,12,14,40,26,...,16,13,11,81,83,72,78,85,1,Jack Butland
2,77,81,75,81,84,73,84,81,82,80,...,48,51,37,10,11,13,8,7,0,Wayne Rooney
3,86,63,74,79,63,78,81,81,74,80,...,78,81,78,8,15,10,13,12,0,Leighton Baines
4,81,57,62,76,64,79,64,57,66,76,...,82,84,85,10,11,8,13,13,0,Danny Rose

### QUESTION 5

**5) By inspecting the clusters and looking up individual players online, try to assign meaningful labels to the clusters.**

**ANSWER**                              
As we can see from part 4, there are 5 distinct clusters that we see the players divided into. Here is some info that we observe from looking at the data:

**1) Cluster 0**
* Players in this cluster have a high (>75) Strength, Standing Tackle, Interceptions, and Short Passing attributes
* These attributes are usually found in defensive midfielders, who sit in front of the defence and provide more cover to them. They can also be Fullbacks, who are defenders who play on the wings and support the attack at times
* Players in this cluster are: Jack Wilshere, Wayne Rooney etc.
* Thus we assign this cluster the name- **MIDFIELDERS / FULLBACKS**

**2) Cluster 1**
* Players in this cluster have a high (>75) GK Diving, GK Positioning, GK Handling, GK Reactions attributes
* These attributes are for Goalkeepers
* Players in this cluster are: Tom Heaton, Jordan Pickford, etc.
* Thus we assign this cluster the name- **GOALKEEPERS**

**3) Cluster 2**
* Players in this cluster have a high (>75) Strength, Agression, Standing Tackle, Sliding Tackle, Interceptions, and Marking attributes
* These attributes are usually found in defenders
* Players in this cluster are: Chris Smalling, John Stones, etc.
* Thus we assign this cluster the name- **DEFENDERS**

**4) Cluster 3**
* Players in this cluster have a high (>75) Agility, Acceleration, Sprint Speed, Ball Control, and Dribbling attributes
* These attributes are usually found in attacking midfielders or forwards, who are the playmakers in a side
* Players in this cluster are: Jamie Vardy, Marcus Rashford etc.
* Thus we assign this cluster the name- **ATTACKING MIDFIELDERS / FORWARDS**

Let us name the players now based on the classification above.

In [24]:
df_attributes['Category'] = df_attributes.kmeans_prediction.apply(lambda x: 'Midfielder / Fullback' if x==0
                                                                  else "Goalkeeper" if x==1
                                                                  else 'Defender' if x==2
                                                                  else 'Attacking Midfielder / Forward')
df_attributes.head()

,Crossing,Finishing,Heading accuracy,Short passing,Volleys,Dribbling,Curve,Free kick accuracy,Long passing,Ball control,...,Standing tackle,Sliding tackle,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,kmeans_prediction,names,Category
0,73,64,58,84,64,82,80,72,80,84,...,63,65,6,15,15,9,11,0,Jack Wilshere,Midfielder / Fullback
1,11,16,12,36,12,21,12,14,40,26,...,13,11,81,83,72,78,85,1,Jack Butland,Goalkeeper
2,77,81,75,81,84,73,84,81,82,80,...,51,37,10,11,13,8,7,0,Wayne Rooney,Midfielder / Fullback
3,86,63,74,79,63,78,81,81,74,80,...,81,78,8,15,10,13,12,0,Leighton Baines,Midfielder / Fullback
4,81,57,62,76,64,79,64,57,66,76,...,84,85,10,11,8,13,13,0,Danny Rose,Midfielder / Fullback

### QUESTION 6

**6) For a new and unknown player, the following attributes are available:**

![fig1.png](images/fig1.png)

**For each of your 5 clusters from Step 4, compute the cluster centroid. Assign the new player to the nearest cluster based on the distance to the cluster centroids, using only the available attributes.**

**ANSWER**                              
To predict the cluster for the player, let us first get the centroids for the clusters.

In [42]:
centroids = kmeans_test.cluster_centers_

output = pd.DataFrame(centroids)

output.columns = ['Crossing','Finishing','Heading accuracy','Short passing','Volleys','Dribbling', 'Curve','Free kick accuracy',
                  'Long passing','Ball control','Acceleration','Sprint speed','Agility','Reactions','Balance','Shot power',
                  'Jumping','Stamina','Strength','Long shots','Aggression','Interceptions','Positioning','Vision','Penalties',
                  'Composure','Marking','Standing tackle','Sliding tackle','GK diving','GK handling','GK kicking',
                  'GK positioning','GK reflexes']

selected_attrib = output[['Crossing', 'Sprint speed','Long shots', 'Aggression','Marking','Finishing','GK handling']]

Now, let us look at the centroids for the given attributes.

In [43]:
selected_attrib

,Crossing,Sprint speed,Long shots,Aggression,Marking,Finishing,GK handling
0,67.036145,68.108434,61.656627,69.463855,64.150602,55.993976,10.740964
1,14.400000,44.628571,14.685714,29.228571,14.200000,14.371429,69.942857
2,47.512605,61.621849,33.042017,72.008403,69.764706,32.890756,11.739496
3,59.706667,76.453333,64.506667,55.660000,29.313333,67.813333,11.140000

Let us now calculate the distances of the attributes from the centroids.

In [47]:
player_attributes = [45, 40, 35, 45, 60, 40, 15]

player_attr = np.zeros((4,7))
player_attr = player_attr + player_attributes
player_dist = selected_attrib - player_attr
player_dist['Mean Distance'] = abs(np.mean(player_dist, axis = 1))

player_dist

,Crossing,Sprint speed,Long shots,Aggression,Marking,Finishing,GK handling,Mean Distance
0,22.036145,28.108434,26.656627,24.463855,4.150602,15.993976,-4.259036,16.735800
1,-30.600000,4.628571,-20.314286,-15.771429,-45.800000,-25.628571,54.942857,11.220408
2,2.512605,21.621849,-1.957983,27.008403,9.764706,-7.109244,-3.260504,6.939976
3,14.706667,36.453333,29.506667,10.660000,-30.686667,27.813333,-3.860000,12.084762

Looking at the mean distances, we can conclude that the player is of **Cluster 2**, i.e. he is a **DEFENDER**.